### 게시글 작성
POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "title" : "blog title",
  "content" : "blog content"
}

### 게시글 조회 API
GET http://localhost:8080/api/articles

### 게시글 단건 조회 API
@id=1
GET http://localhost:8080/api/articles/{{id}}

### 게시글 단건 삭제 API
DELETE http://localhost:8080/api/articles/{{id}}

### 게시글 단건 수정 API
PUT http://localhost:8080/api/articles/{{id}}
Content-Type: application/json

{
  "title" : "변경된 제목",
  "content" : "변경된 내용"
}

### 댓글 생성 API
@articleId=1
POST http://localhost:8080/api/articles/{{articleId}}/comments
Content-Type: application/json

{
  "body": "댓글 내용!!"
}

### 댓글 단건  조회 API
@commentId=1
GET http://localhost:8080/api/comments/{{commentId}}

### 댓글 수정 API
PUT http://localhost:8080/api/comments/{{commentId}}
Content-Type: application/json

{
  "body" : "수정 댓글 내용@!"
}

### 댓글 삭제 API
DELETE http://localhost:8080/api/comments/{{commentId}}

### 게시글과 댓글 정보를 한번에 조회하는 API (하나의 게시글의 댓글(리스트) 조회)
GET http://localhost:8080/api/articles/{{articleId}}/comments